[project]
name = "update_repos"
version = "0.1.1"
description = "Find and update git repositories."
dependencies = ["GitPython~=3.1", "typing-extensions~=4.12"]
requires-python = ">= 3.13"

[tool.ruff]
line-length = 119
