[project]
name = "update_repos"
version = "0.1.0"
description = "Find and update git repositories."
dependencies = ["GitPython~=3.1"]
requires-python = ">= 3.9"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 119
